# Generated by Django 5.0.6 on 2024-07-05 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0002_alter_cliente_fecha_registro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='cliente',
        ),
        migrations.AlterUniqueTogether(
            name='detalleventa',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='detalleventa',
            name='factura',
        ),
        migrations.RemoveField(
            model_name='detalleventa',
            name='producto',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Factura',
        ),
        migrations.DeleteModel(
            name='DetalleVenta',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
